#!/bin/bash

#SBATCH --job-name=dhruvsrikanth-hpc
#SBATCH --output=batch_file.stdout
#SBATCH --error=batch_file.stderr
#SBATCH --time=00:15:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1


module load gcc
module load cuda

nvcc ./ray_tracing.cu -o ./ray_tracing.out -O3 -use_fast_math -extra-device-vectorization -lm -arch=sm_60 -std=c++11

./ray_tracing.out 1e7 1000 1000